### ISSUE TITLE
Incompatibilty with Node v16

### ISSUE THREAD

**Issue by ajeetraina** [shamin/redis-realtime#1]
My Environment:

## NPM

```
npm@7.11.2 /usr/local/lib/node_modules/npm
```
## NodeJS

```
node
Welcome to Node.js v16.0.0.
Type ".help" for more information.
> 
```
Tried running:

```
npm start              

> realtime-backend@0.0.1 start
> nodemon src/index.ts

[nodemon] 2.0.7
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: ts,json
[nodemon] starting `ts-node src/index.ts`

/Users/ajeetraina/projects/redis-realtime/node_modules/ts-node/src/index.ts:513
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
src/index.ts:4:27 - error TS2307: Cannot find module '@space-kit/redis-realtime-node' or its corresponding type declarations.

4 import redisRealtime from '@space-kit/redis-realtime-node'
                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    at createTSError (/Users/ajeetraina/projects/redis-realtime/node_modules/ts-node/src/index.ts:513:12)
    at reportTSError (/Users/ajeetraina/projects/redis-realtime/node_modules/ts-node/src/index.ts:517:19)
    at getOutput (/Users/ajeetraina/projects/redis-realtime/node_modules/ts-node/src/index.ts:752:36)
    at Object.compile (/Users/ajeetraina/projects/redis-realtime/node_modules/ts-node/src/index.ts:968:32)
    at Module.m._compile (/Users/ajeetraina/projects/redis-realtime/node_modules/ts-node/src/index.ts:1056:42)
    at Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/ajeetraina/projects/redis-realtime/node_modules/ts-node/src/index.ts:1059:12)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Function.Module._load (node:internal/modules/cjs/loader:828:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
[nodemon] app crashed - waiting for file changes before starting...
^C
ajeetraina@Ajeets-MacBook-Pro realtime-be % ls
```

Does it mean I strictly need to use Node v14?

**Comment by ajeetraina** [comment]
@shamin Any comments?

**Comment by shamin** [comment]
Hi Ajeet,

Apologies for the late reply. I was a little busy last week and missed this. I did take a look and recognised that I have missed adding some steps in documentation to run the project locally.

Before running the realtime-backend or realtime-frontend, You have to build
the packages. To do that go to each of the packages folders `
packages/redis-realtime-node` and `packages/redis-realtime-react` then run
npm install followed by npm run build. I have updated the readme
<https://github.com/shamin/redis-realtime/blob/main/README.md#run-examples-locally>
to have these commands.

If you have more issues please let me know.

**Comment by ajeetraina** [comment]
@shamin Got it fixed. Thanks.
