### ISSUE TITLE
error: [plugin: vite:dep-scan] Failed to resolve entry for package "@space-kit/redis-realtime-react"

### ISSUE THREAD

**Issue by xdien** [shamin/redis-realtime#2]
I can't run the command
`npm run dev`

```> realtime-frontend@0.0.0 dev
> vite

 > node_modules/vite/dist/node/chunks/dep-66eb515d.js:32070:14: error: [vite:dep-scan] Failed to resolve entry for package "@space-kit/redis-realtime-react". The package may have incorrect main/module/exports specified in its package.json.
    32070 │         throw new Error(`Failed to resolve entry for package "${id}". ` +
          ╵               ^
    at resolvePackageEntry (/home/xdien/workspace/redis-realtime/examples/realtime-fe/node_modules/vite/dist/node/chunks/dep-66eb515d.js:32070:15)
    at tryNodeResolve (/home/xdien/workspace/redis-realtime/examples/realtime-fe/node_modules/vite/dist/node/chunks/dep-66eb515d.js:31907:11)
    at Context.resolveId (/home/xdien/workspace/redis-realtime/examples/realtime-fe/node_modules/vite/dist/node/chunks/dep-66eb515d.js:31790:28)
    at Object.resolveId (/home/xdien/workspace/redis-realtime/examples/realtime-fe/node_modules/vite/dist/node/chunks/dep-66eb515d.js:43659:55)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async resolve (/home/xdien/workspace/redis-realtime/examples/realtime-fe/node_modules/vite/dist/node/chunks/dep-66eb515d.js:43862:26)
    at async /home/xdien/workspace/redis-realtime/examples/realtime-fe/node_modules/vite/dist/node/chunks/dep-66eb515d.js:43966:34
    at async callback (/home/xdien/workspace/redis-realtime/examples/realtime-fe/node_modules/esbuild/lib/main.js:724:28)
    at async handleRequest (/home/xdien/workspace/redis-realtime/examples/realtime-fe/node_modules/esbuild/lib/main.js:595:30)

   node_modules/vite/dist/node/chunks/dep-66eb515d.js:43956:18: note: This error came from the "onResolve" callback registered here
    43956 │             build.onResolve({
          ╵                   ~~~~~~~~~
    at setup (/home/xdien/workspace/redis-realtime/examples/realtime-fe/node_modules/vite/dist/node/chunks/dep-66eb515d.js:43956:19)
    at handlePlugins (/home/xdien/workspace/redis-realtime/examples/realtime-fe/node_modules/esbuild/lib/main.js:686:7)
    at Object.buildOrServe (/home/xdien/workspace/redis-realtime/examples/realtime-fe/node_modules/esbuild/lib/main.js:903:44)
    at /home/xdien/workspace/redis-realtime/examples/realtime-fe/node_modules/esbuild/lib/main.js:1444:17
    at new Promise (<anonymous>)
    at Object.build (/home/xdien/workspace/redis-realtime/examples/realtime-fe/node_modules/esbuild/lib/main.js:1443:14)
    at Object.build (/home/xdien/workspace/redis-realtime/examples/realtime-fe/node_modules/esbuild/lib/main.js:1334:51)
    at /home/xdien/workspace/redis-realtime/examples/realtime-fe/node_modules/vite/dist/node/chunks/dep-66eb515d.js:43816:54
    at Array.map (<anonymous>)

   src/main.tsx:4:33: note: The plugin "vite:dep-scan" was triggered by this import
        4 │ import { RealtimeProvider } from '@space-kit/redis-realtime-react'
          ╵                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

- npm@7.24.1

Steps:
```
git clone https://github.com/shamin/redis-realtime
cd redis-realtime/exmaples/realtime-fe/
npm install
npm run dev 
```

**Comment by xdien** [comment]
Duplicate  https://github.com/shamin/redis-realtime/issues/1
